---
- name: tasks for assign1 on slave1
  hosts: slave1
  become: true
  tasks:
  - name: install Java
    apt: name=openjdk-11-jdk state=latest
    
- name: Install MySQL
  hosts: your_mysql_servers
  become: true  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes  # Update apt package cache

    - name: Install MySQL packages
      apt:
        name: 
          - mysql-server   
          - mysql-client   
        state: present    

