---
- name: tasks for assign1 on slave1
  hosts: slave1
  become: true
  tasks:
  - name: install Java
    apt: name=openjdk-11-jdk state=latest
    
- name: tasks for assign1 on slave1
  hosts: slave1
  become: true
  tasks:
  - name: install mysql
    apt: name=mysql-server state=latest
